// vuejs/src/App.vue
<script setup></script>

<template>
  <div style="padding: 2rem; font-family: system-ui, sans-serif;">
    <h1 style="color: #42b883; font-size: 2rem; font-weight: bold;">
      it works!
    </h1>
    <p style="margin-top: 1rem; color: #666;">
      Your Vue.js application is running successfully.
    </p>
  </div>
</template>

<style scoped></style>

// react/src/App.jsx
function App() {
  return (
    <div style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1 style={{ color: '#0070f3', fontSize: '2rem', fontWeight: 'bold' }}>
        React - It works!
      </h1>
      <p style={{ marginTop: '1rem', color: '#666' }}>
        Your React application is running successfully.
      </p>
    </div>
  );
}

export default App;
